services:
  - type: web
    name: aniwatch-api
    runtime: docker
    repo: https://github.com/robertteah/aniwatch-api
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 4000
